[package]
name = "nes_rs"
version = "0.1.0"
authors = ["Eli Lipsitz <eli.lipsitz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
clap = "2.33.1"
hound = "3.4.0"
