[package]
name = "nes_wasm"
version = "0.1.0"
authors = ["Eli Lipsitz <eli.lipsitz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nes_core = { path = "../nes_core" }
wasm-bindgen = "0.2.70"